

// This script has been auto-generated by Open-Dashboard. Never attempt to
// modify this.
// Suraj Vijayan
//
function get_theme_cookie()
{
    var cookieName = 'themeID';
    var search = new RegExp(cookieName + '=([^;]*)');
    var matches = search.exec(document.cookie);
    var themeId = (matches ? matches[1] : '') || '';
    if(themeId == '')
		themeId = 'smoothness';
    set_theme(themeId);
}
/***************************************************************************************************/

function set_theme(id)
{
    switch(id)
    {
        case 'uidarkness':
            AmCharts.theme = AmCharts.themes.black;
        case 'dotluv':
            AmCharts.theme = AmCharts.themes.dark;
            break;
        case 'darkhive':
            AmCharts.theme = AmCharts.themes.black;
            break;
        case 'blacktie':
            AmCharts.theme = AmCharts.themes.dark;
            break;
        case 'uilightness':
        case 'smoothness':
            AmCharts.theme = AmCharts.themes.light;
            break;
        case 'cupertino':
            AmCharts.theme = 'black';
            $('.chosen-choices li').css('background','LightBlue');
            break;
        default:
            AmCharts.theme = AmCharts.themes.light;
            $('.chosen-choices li').css('background','LightBlue');
            break;
    }
}
/***************************************************************************************************/

function fn(id,name,url)
{
    window.location.reload(true);
}
/***************************************************************************************************/

function resize_div() 
{
	vpw = $(window).width();
	vph = $(window).height();
	vph = vph - 100;
	$('#scroll').css({'height': vph + 'px'});
}
/***************************************************************************************************/

function serialize_forms(widgets_array,no_widgets)
{
var i;
/*
    for(i = 0;i < no_widgets;i++)
    {
        form_id = '#form_' + widgets_array[i].name; 
        var args = $(form_id).serializeArray();
        console.log('ID:'+i+' FORM:'+form_id)
        console.log(JSON.stringify(args));
    }
*/
	$('form').each
	(
   		function(index)
		{  
        	form_id = '#' + this.id; 
        	var args = $(form_id).serializeArray();
        	console.log('ID:'+index+' FORM:'+form_id)
        	console.log(JSON.stringify(args));
    	}
	);
}
/***************************************************************************************************/

function dispatch_events(ROOT)
{
var w1,h1;
var no_widgets = 4;

var widgets_array = [
	{no:"0",div:"DIV_0",name:"get_country_fact_sheets",type:"chart"},
	{no:"1",div:"DIV_1",name:"country_area",type:"chart"},
	{no:"2",div:"DIV_2",name:"country_gdp",type:"chart"},
	{no:"3",div:"DIV_3",name:"countries_data",type:"grid"}
];

var fscreen_flag = false;
$.themes.setDefaults({themeBase: '../jquery-ui-themes-1.12.1/themes/',
                      previews: '../js/themes-preview.gif',
                      icons: '../js/themes.gif',
                      cookieExpiry: 7,
                      themeFile: 'jquery-ui.min.css',
                      showPreview: false,
					  defaultTheme:'smoothness',
                      onSelect:fn});
$('#hoverThemes').hover(function() { $('#selectThemes').toggle()});
$('#selectThemes').hide();
$(window).onresize = function(event) 
{
	resize_div();
};

AmCharts.ready(function(){
	resize_div();
	$(window).on('resize', function()
	{
		resize_div();
	});
    var w = $(window).width()-55;
    var h = $(window).height()-120;
    var div_id = '';
    $('.fa-expand').click(function()
    {
        div_id = $(this).attr('id').split('_head')[0];
        $(this).toggleClass('fa-compress');
        if(fscreen_flag == false) // Maximizing
        {
            fscreen_flag = true;
            w1 =  $('#'+div_id).css('width');
            h1 =  $('#'+div_id+'_outer').css('height');
            $('#'+div_id+'_outer').animate({height:h}, 300,
            function()
            {
                for(i = 1;i <= no_widgets;i++)
                {
                    var tdiv = '#DIV_'+i;
                    if(tdiv != '#'+div_id)
                        $(tdiv+'_outer').fadeOut(1600, 'linear');
                }
            });
			id = div_id.split('DIV_')[1];
            if(widgets_array[id-1].type == 'chart')
                $('#'+div_id).animate({width:w}, 300);
            else
                $('table.'+div_id).attr('width', w);
            $('#'+div_id).addClass('active');
            $('#'+div_id).css({'z-index': '9999'});
        }
        else
        {
            fscreen_flag = false;
            div_id = $(this).attr('id').split('_head')[0];
            $('#'+div_id+'_outer').animate({height:h1}, 300,
            function()
            {
                for(i = 1;i <= no_widgets;i++)
                {
                    var tdiv = '#DIV_'+i;
                    if(tdiv != '#'+div_id)
                        $(tdiv+'_outer').fadeIn(1600, 'linear');
                }
            });
            $('#'+div_id).animate({width:w1}, 300);
            $('#'+div_id).addClass('active');
            $('#'+div_id).css({'z-index': '9999'});
        }
    });
    get_theme_cookie();
    $('#selectThemes').themes({themes: ['darkhive','cupertino','smoothness','dotluv']});
    $('#scroll').css({'z-index':'1','position':'absolute'});
    $( '#list1 li').click(function()
    {
        $('#list1').option = $(this).text();
    alert('Doing Serialize!');
    serialize_forms(widgets_array,no_widgets);
    });
    $('.date_input').datepicker({dateFormat: 'yy-mm-dd'}).attr('readonly', 'true');
	$('.chosen-select').chosen({max_selected_options:7}).change();
	$("h4#date").text("Last Updated: "+Date());
	$('#DIV_1').addClass('big_div_class');
	$('#DIV_1').show();
	get_country_fact_sheets_submit(ROOT,'DIV_1','#form_get_country_fact_sheets','#click_get_country_fact_sheets');
	$('#form_get_country_fact_sheets').trigger('submit');
	$("h4#date").text("Last Updated: "+Date());
	$('#DIV_2').addClass('big_div_class');
	$('#DIV_2').show();
	country_area_submit(ROOT,'DIV_2','#form_country_area','#click_country_area');
	$('#form_country_area').trigger('submit');
	$("h4#date").text("Last Updated: "+Date());
	$('#DIV_3').addClass('big_div_class');
	$('#DIV_3').show();
	country_gdp_submit(ROOT,'DIV_3','#form_country_gdp','#click_country_gdp');
	$('#form_country_gdp').trigger('submit');
	$("h4#date").text("Last Updated: "+Date());
	$('#DIV_4').addClass('big_div_class');
	countries_data_submit(ROOT,'DIV_4','#form_countries_data');
	$('#form_countries_data').trigger('submit');
	$("h4#date").text("Last Updated: "+Date());
});
}
/***************************************************************************************************/
